ingress:
  - hostname: ai.uurl.uz
    service: http://host.docker.internal:3001

  - hostname: "*.uurl.uz"
    service: http://host.docker.internal:3000

  - hostname: uurl.uz
    service: http://host.docker.internal:3000

  - service: http_status:404
